export const defaultState = {
  listOfTeams: [],
  listOfPlayers: [],
  rivalPlayers: [],
  rivalClub: [],
  myTeamPlayers: [],
  myClub: [],
  zones: Array(6).fill(null),
  indexOfZones: [5, 2, 1, 0, 3, 4],
  myTeamZones: Array(6).fill(null),
  sequanceOfZones: [5, 2, 1, 0, 3, 4],
  playerInfo: null,
  userInfo: null,
  isRegistratedUser: false,
  changeLanguage: false,
  isShowedTutorial: false,
};
